version: '3.1'

services:
  web:
    build:
      context: django_project
    command: ./utils/wait-for.sh db:5432 -t 60 -- python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./django_project:/project
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.dev

  worker:
    build: django_project
    command: ./utils/wait-for.sh db:5432 -t 60 -- celery worker -A localities -l info -c 1
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./django_project:/project
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.dev

  scheduler:
    build: django_project
    command: celery beat -A localities -l info
    depends_on:
      - rabbitmq
    volumes:
      - ./django_project:/project
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.dev

  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_NODENAME=rabbitmq

  db:
    image: mdillon/postgis:9.4-alpine
    environment:
      - POSTGRES_USER=docker
      - POSTGERS_PASSWORD=docker

