# Generated by Django 3.2.18 on 2023-09-21 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthsiteSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('license', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Healthsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.CharField(choices=[('clinic', 'Clinic'), ('doctors', 'Doctors'), ('hospital', 'Hospital'), ('dentist', 'Dentist'), ('pharmacy', 'Pharmacy')], default='hospital', help_text='amenity=clinic,doctors,hospital,dentist,pharmacy', max_length=512)),
                ('healthcare', models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('pharmacy', 'Pharmacy'), ('hospital', 'Hospital'), ('clinic', 'Clinic'), ('dentist', 'Dentist'), ('physiotherapist', 'Physiotherapist'), ('alternative', 'Alternative'), ('laboratory', 'Laboratory'), ('optometrist', 'Optometrist'), ('rehabilitation', 'Rehabilitation'), ('blood_donation', 'Blood Donation'), ('birthing_center', 'Birthing Center')], default='hospital', help_text='healthcare=doctor,pharmacy,hospital,clinic,dentist,physiotherapist,alternative,laboratory,optometrist,rehabilitation,blood_donation,birthing_center', max_length=512, null=True)),
                ('name', models.CharField(max_length=512)),
                ('operator', models.CharField(blank=True, max_length=512, null=True)),
                ('administrative_code', models.CharField(blank=True, max_length=32, null=True)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('changeset_id', models.IntegerField(blank=True, null=True)),
                ('changeset_version', models.IntegerField(blank=True, null=True)),
                ('changeset_timestamp', models.DateTimeField(blank=True, null=True)),
                ('changeset_user', models.CharField(blank=True, max_length=512, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthsites.healthsitesource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
