version: '2.1'
volumes:
  geoserver-data:
services:

  data-dir-conf:
    image: geosolutionsit/geoserver_data:2.13.x
    restart: on-failure
    command: /bin/true
    volumes:
      - geoserver-data:/geoserver_data/data

  geoserver:
    image: geosolutionsit/geoserver-docker:2.13.x
    ports:
      - 49364:8080
    depends_on:
      - osm-db
      - data-dir-conf
    volumes:
      - geoserver-data:/geoserver_data/data
