SECRET_KEY = ''
DISQUS_WEBSITE_SHORTNAME = ''

SOCIAL_AUTH_TWITTER_KEY = ''
SOCIAL_AUTH_TWITTER_SECRET = ''

SOCIAL_AUTH_GITHUB_KEY = ''
SOCIAL_AUTH_GITHUB_SECRET = ''

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = ''
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = ''
SOCIAL_AUTH_FACEBOOK_KEY = ''
SOCIAL_AUTH_FACEBOOK_SECRET = ''

SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = ''
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = ''

SOCIAL_AUTH_OPENSTREETMAP_KEY = ''
SOCIAL_AUTH_OPENSTREETMAP_SECRET = ''

SOCIAL_AUTH_OPENSTREETMAP_STAGING_KEY = ''
SOCIAL_AUTH_OPENSTREETMAP_STAGING_SECRET = ''

GATHER_USERNAME = ''
GATHER_PASSWORD = ''

GOOGLE_MAPS_API_KEY = ''

CHAPCHA_SITE_KEY = ''
CHAPCHA_SECRET_KEY = ''
