# Generated by Django 3.2.18 on 2023-02-22 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userapikey_allow_write'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='allow_write',
            field=models.BooleanField(default=False, help_text='allow this api key to write data'),
        ),
        migrations.CreateModel(
            name='ApiKeyRequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('url', models.TextField()),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userapikey')),
            ],
        ),
        migrations.CreateModel(
            name='ApiKeyAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('counter', models.IntegerField(default=0)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userapikey')),
            ],
        ),
    ]
