# Generated by Django 3.2.18 on 2023-02-24 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230222_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeyEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=512)),
                ('contact_email', models.EmailField(max_length=254)),
                ('organisation_name', models.CharField(max_length=512)),
                ('organisation_url', models.CharField(max_length=512)),
                ('project_url', models.CharField(help_text='web site or project URL for API will be used', max_length=512)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False, help_text='When approved, the api_key will be created and activated')),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userapikey')),
            ],
        ),
    ]
